### ISSUE TITLE
remove "development" docs and fix redirect

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf.org#9]
I’ve been getting reports that Google is directing people to the “development” version of the docs, even though we don’t publish links to that on the main site any more. I also see that [warewulf.org](http://warewulf.org/) is trying to redirect people from development to main, but that doesn’t seem to actually be working.

@brianclemens could you fix the redirect from https://warewulf.org/docs/development/* to https://warewulf.org/docs/main/ and remove the development version of the docs? https://github.com/warewulf/warewulf.org/tree/main/static/docs/development

**Comment by brianclemens** [comment]
Fixed in 79789ba. I believe it's possible to get GitHub Pages to do server-side redirects, but in the interest of expediency I just symlinked all the old pages to a page that redirects to the new documentation root. Debated whether to link each old item to it's corresponding new URL, but figured it would end up troublesome if anything is renamed.

**Comment by NeilHanlon** [comment]
> Fixed in [79789ba](https://github.com/warewulf/warewulf.org/commit/79789ba045d76d4ca062c5d24302c100b8e31e75). I believe it's possible to get GitHub Pages to do server-side redirects, but in the interest of expediency I just symlinked all the old pages to a page that redirects to the new documentation root. Debated whether to link each old item to it's corresponding new URL, but figured it would end up troublesome if anything is renamed.

could be worth looking at deploying onto Fastly now that they also have a free plan; could codify the SSRs in there (and depoy from this repo).

we can talk :D
